### PR TITLE
Add examples

### LINKED ISSUE #3: Add example(s)
There's a placeholder example but it does nothing. There were no examples when the crypto package was part of the standard library, so none got moved over. I set up the placeholder so that when examples are added, they would be compiled by CI without any additional changes needing to be made.

### PR DESCRIPTION
**Pull request by Mark1626**
Adding examples and updating README. I'm a bit new to `ponylang`, let me know if you want to change anything

Closes #3

### CODE REVIEW

**Comment by Mark1626** [comment]
Not sure why this is failing in the pipeline now

**Comment by SeanTAllen** [comment]
Hi @Mark1626, Thanks for this. I'll take a look at the examples later. 

You can remove the examples from being in the README as well, "just" in the examples folder is fine.

**Comment by SeanTAllen** [comment]
The CI failure is from a mistake in the `Makefile` that I missed when I put it together.

@Mark1626 can you change:

`	$(PONYC) -o $(BUILD_DIR) $(EXAMPLES_DIR)/$*`

on line 54 of the Makefile to:

`	$(PONYC) $(SSL) -o $(BUILD_DIR) $(EXAMPLES_DIR)/$*`

That should fix the CI failure.

**Comment by SeanTAllen** [comment]
These seem like perfectly good initial examples, more could be added later.

With the README change and the fix to the Makefile this looks good to go.

Thanks @Mark1626.

**Comment by Mark1626** [comment]
Sure, one more thing about the folder name is it ok to be in kebab case, I saw example folders in other packages in snake case

**Comment by SeanTAllen** [comment]
Kebab is fine. There's a mix across projects for the examples that needs to be resolved. Given that, leave as is until such time as we sort that out.

**Comment by SeanTAllen** [comment]
Awesome. Thank you @Mark1626.

**Pull request merged**
